### PR TITLE
Create friendly_setup.md

### PR DESCRIPTION
**Pull request by GamerZ14**
Advanced guide on setting up Fosscord server by Gamer Z

### CODE REVIEW

**Comment by ChrisChrome** [comment]
This is just the terminal setup with postgres setup included, at least at first glance

**Comment by GamerZ14** [comment]
It does explain how to point it to a domain, and it's better explained to the point that even those with no idea how to use Linux can use it and set it up for themself. This stops the repeated question on how to set it up, which has been repeatedly asked on the server.

**Comment by ImAaronFR** [comment]
I'd like to point out that similar documentations already exists

https://docs.fosscord.com/setup/server/
https://docs.fosscord.com/setup/HTTPS/

and other docs on github

yet not a bad idea

**Review by GamerZ14 — COMMENTED** [review]
Added few more points

**Comment by GamerZ14** [comment]
> I'd like to point out that similar documentations already exists
> 
> https://docs.fosscord.com/setup/server/ https://docs.fosscord.com/setup/HTTPS/
> 
> and other docs on github
> 
> yet not a bad idea

True but more noob-friendly :)

**Comment by GamerZ14** [comment]
See all I am trying to do is a 1 stop solution on how to set it up. For those who know what they are doing this might be useless. But for those who have no idea what they are doing and want to set it up this guide will surely help them. After all I learnt from my teachers The Arcane Brony and Chris Chrome and that knowledge I am painting it to a canvas in a more refined manner.

**Comment by ImAaronFR** [comment]
i see what you are trying to do. I recommend creating a table of contents for more organized doc and renaming the doc to something related to doc like friendly_setup.md or something like that.

**Comment by GamerZ14** [comment]
sure will try

**Comment by GamerZ14** [comment]
its now "friendly_setup.md" if you have any other suggestions please let me know!

**Review by NotLazy — APPROVED** [review]
This would be super helpful in the docs. contains way more helpful information than current setup instructions, such as how to setup a database, since the server warns against using sqlite but doesn't tell you how to tell it where to find the database.

**Comment by GamerZ14** [comment]
Yes sir! I will be adding more information about how to edit certain things and how they can do things soon after this part of the pr gets accepted.

**Review by ImAaronFR — APPROVED** [review]
nice job!

**Comment by haydenwalker980** [comment]
Not to be one of those annoying grammar people but you have Fosscord misspelled. I'll fix it.

**Review by haydenwalker980 — APPROVED** [review]

**Comment by AToska21** [comment]
looks good

**Comment by erkinalp** [comment]
superceded by #24

**Pull request closed without merging**
