### PR TITLE
Improve client documentation

### PR DESCRIPTION
**Pull request by bitfl0wer**
I felt that a lot of info about how to build and contribute to the client was missing from the official fosscord-docs, so I added some!

Also: I added mkdocs-macros-plugin as a requirement to build/deploy this project. I have done this to allow for the definition of jinja2-like variables in the mkdocs.yml file. I have replaced every occurence of the word "Fosscord" with a {{ name }} variable, which will probably aid during the upcoming name change (#59) of the project. Edit just one variable to change every occurence of "Fosscord' within the docs! This only affects `.md`-files within the /docs directory. The project README.md is unaffected, for example, as are 

- mkdocs.yml
- .github/FUNDING.yml
- .github/workflows/build.yml
- .vscode/settings.json
- docs/assets/js/missingroutes.js

Please let me know what you think of this change. I am happy to revert the variable-thing, if wanted.

### CODE REVIEW

**Comment by Puyodead1** [comment]
Why did you capitalize fosscord in urls?

**Comment by bitfl0wer** [comment]
I can change that by using {{ name.lower() }} instead of {{ name }}. As far as I have seen, it has not affected if any links work or not, but it would probably make more sense to convert them to lowercase.

As to why I've done this in the first place: I used search/replace to replace Fosscord with the variable, this result wasn't intended. I used name.lower() In the client doc I have written, though.

**Comment by bitfl0wer** [comment]
Please let me know if you want me to change the Fosscord-mentions in links to lowercase. :)

**Comment by bitfl0wer** [comment]
Good that you thought of this, @Puyodead1; There were several instances, where "Project-name" was used, but "project-name" (lowercase) was appropriate. I have changed all these occurrences.

**Comment by MaddyUnderStars** [comment]
I would really have preferred if the macro changes and the client docs were separate PRs.

I don't think it's a good idea to compose macros for URLs or project names like `{{ name }}-server`. It might be better to have macros for the different urls and such, for example `{{ server-repo }}`?

I don't think you need to 'directly quote' puyo in the client docs, just write that in bullet points or whatever

It seems like your prettier isn't following our prettierrc?

**Comment by bitfl0wer** [comment]
I will look into these things.

**Pull request closed without merging**
