### PR TITLE
Fixed typo in cdn explanation in resources 

### PR DESCRIPTION
**Pull request by Quik2007**

### CODE REVIEW

**Comment by Justman10000** [comment]
@Flam3rboy

Can you take a look at this 🙂?

**Comment by TheArcaneBrony** [comment]
dont ping random people @Justman10000

**Comment by Justman10000** [comment]
> dont ping random people @Justman10000

Random? It's a project maintainer, but chin up!

**Comment by Justman10000** [comment]
> dont ping random people @Justman10000

Random? It's a project maintainer, like you!

**Pull request closed without merging**
