### PR TITLE
Update rights.md

### PR DESCRIPTION
**Pull request by BoQsc**

### CODE REVIEW

**Comment by Justman10000** [comment]
@Flam3rboy

Can you take a look at this 🙂?

**Comment by TheArcaneBrony** [comment]
dont ping random people @Justman10000

**Comment by Justman10000** [comment]
> dont ping random people @Justman10000

Random? It's a project maintainer, but chin up!

**Comment by Justman10000** [comment]
> dont ping random people @Justman10000

Random? It's a project maintainer, like you!

**Comment by MaddyUnderStars** [comment]
Unneeded now, thanks to latest rewrite. Thanks for your PR, though.

**Pull request closed without merging**
