### PR TITLE
ENDPOINT Changing Guide

### PR DESCRIPTION
**Pull request by ImAaronFR**
How to change your Discord client ENDPOINT to your Fosscord instance ENDPOINT

### CODE REVIEW

**Comment by omxpro** [comment]
Seems helpful but why need client when you already have web working like a charm

**Comment by omxpro** [comment]
They both look and are the same on perform wise

**Comment by ImAaronFR** [comment]
> 

someone might want to use the client instead of browser or a whole instance just using the client instead of browser, it's good to be here yk

**Comment by omxpro** [comment]
> > 
> 
> someone might want to use the client instead of browser or a whole instance just using the client instead of browser, it's good to be here yk

I don't think this pr is needed right now (it's up to mods tho) so maybe some mod can draft/save this or for later use in future? (Also this is my opinion don't come to me asking why I am saying this *cough*)

**Comment by ImAaronFR** [comment]
> > > 
> > 
> > 
> > someone might want to use the client instead of browser or a whole instance just using the client instead of browser, it's good to be here yk
> 
> I don't think this pr is needed right now (it's up to mods tho) so maybe some mod can draft/save this or for later use in future? (Also this is my opinion don't come to me asking why I am saying this _cough_)

personally i think it's good to be here just in case someone needed it, i personally find it more nice to use the client instead of the browser...

**Comment by TheArcaneBrony** [comment]
If anything, I'd add a warning to do this on a secondary install of discord, be it discordptb, discordcanary or discorddevelopment

**Comment by omxpro** [comment]
> > > > 
> > > 
> > > 
> > > someone might want to use the client instead of browser or a whole instance just using the client instead of browser, it's good to be here yk
> > 
> > 
> > I don't think this pr is needed right now (it's up to mods tho) so maybe some mod can draft/save this or for later use in future? (Also this is my opinion don't come to me asking why I am saying this _cough_)
> 
> personally i think it's good to be here just in case someone needed it, i personally find it more nice to use the client instead of the browser...

Yeah draft or saves it

**Comment by TheArcaneBrony** [comment]
Are we just doing email replies now? lol

**Comment by Xenorio** [comment]
related to #8

**Comment by erkinalp** [comment]
superceded by #24

**Pull request closed without merging**
