### PR TITLE
Added 'How to edit Database.db (database guide)' in docs

### PR DESCRIPTION
**Pull request by omxpro**
Hey hi, so this is not really done, there is 2 more topics left which ill do when I am free tmr is a holiday for me anyway, also here is a demo https://omxpro.github.io/fosscord-docs/setup/database/, I made this or just to show my progress

### CODE REVIEW

**Comment by omxpro** [comment]
> This was requested by @ChrisChrome to remove the download's and update it with terminal

Talking about https://github.com/fosscord/fosscord-docs/pull/23/commits/01ba54d65f789f460c36059b1762aa02c6f102aa

**Comment by omxpro** [comment]
Pr is ready to review and merge

**Comment by omxpro** [comment]
Wait 2 more days I have to do some stuff

**Comment by TheArcaneBrony** [comment]
Hey, could you add documentation on how to set up postgres/mariadb?

**Comment by omxpro** [comment]
> Hey, could you add documentation on how to set up postgres/mariadb?

Nope, cuz idk how to add them ;-;

**Pull request closed without merging**
